name: Flutter CI

on:
  push:
    branches: [master, frontend_branch]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.4"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (non-blocking)
        run: flutter analyze || true

      - name: Run tests
        run: flutter test

      - name: Build Web Release
        run: flutter build web --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: frontend/build/web